### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by josemsanchez** [josemsanchez/random-quote-machine#1]
Format text, include project information and add the following screenshots.

![RandomQuotes1](https://user-images.githubusercontent.com/10883694/108746677-8e3c5580-7534-11eb-8128-487ac7f898dc.png)
![RandomQuotesTwitter](https://user-images.githubusercontent.com/10883694/108746691-92687300-7534-11eb-8770-73072d93b523.png)

**Comment by truedamagee** [comment]
Hi! Add a mark twain quote

**Comment by luccas13** [comment]
Hi, 
can i work on this?

**Comment by josemsanchez** [comment]
It's all yours @luccas13
